add_newline = true

[conda]
symbol = ' '
ignore_base = true

[character]
success_symbol = '[❯](bold green) '
error_symbol = '[✗](bold red) '

[cmd_duration]
min_time = 500

[directory]
read_only = ' '

[git_branch]
symbol = ' '

[hostname]
ssh_only = true
style = 'bold fg:69'

[memory_usage]
threshold = 75
symbol = ' '
disabled = false

[package]
symbol = ' '

[python]
symbol = ' '

[rust]
symbol = ' '

[status]
format = '[$status]($style) '
disabled = false

[username]
show_always = false
format = '[$user]($style)@'
style_user = 'bold fg:75'
